exports.usernames = [
    "Abyssinian",
    "Australian Mist",
    "Balinese",
    "Bengal",
    "Birman",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Chinchilla",
    "Cornish Rex",
    "Devon Rex",
    "Exotic Shorthair",
    "Foreign White",
    "Japanese Bobtail",
    "Korat",
    "Maine Coon",
    "Manx",
    "Moggie",
    "Munchkin",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental",
    "Persian",
    "Ragdoll",
    "Russian Blue",
    "Scottish Fold",
    "Scottish Shorthair",
    "Siamese",
    "Siberian Forest Cat",
    "Singapura",
    "Snow Shoe",
    "Somali",
    "Sphynx",
    "Tiffanie",
    "Tonkinese",
    "Turkish Van"
]
